Wave-Play/robo.js

packages/create-robo/src/robo.ts
Updated prettier file name to be a MJS instead of a JS file.
=> Update prettier file name

.changeset/silver-impalas-share.md, packages/robo/src/cli/commands/add.ts, packages/robo/src/cli/commands/remove.ts
Fix: Added possibility for add command to have arguments.
Fix: Added possibility for remove command to have arguments.
=> Added option for positional args.

HACKTOBERFEST.md
🚀 Add **Emoji Reaction Plugin** to Hacktoberfest.md
- **Name**: Emoji Reaction Plugin
- **Package**: [emoji-reaction-plugin](https://www.npmjs.com/package/emoji-reaction-plugin)
- **Description**: Make your conversations fun and interactive with various emoji based reactions.
- **Contact**: bekool.sh
=> Add Emoji Reaction Plugin

templates/economy-bot/.eslintignore, templates/economy-bot/.eslintrc.json, templates/economy-bot/README.md, templates/economy-bot/config/robo.mjs, templates/economy-bot/package.json, templates/economy-bot/prettier.config.mjs, templates/economy-bot/src/commands/balance.ts, templates/economy-bot/src/commands/daily.ts, templates/economy-bot/src/commands/deposit.ts, templates/economy-bot/src/commands/ping.ts, templates/economy-bot/src/commands/roll.ts, templates/economy-bot/src/commands/roll_dice.ts, templates/economy-bot/src/commands/share.ts, templates/economy-bot/src/commands/withdraw.ts, templates/economy-bot/src/middleware/isPlayer.ts, templates/economy-bot/src/utils.ts, templates/economy-bot/tsconfig.json
---
I've created a new template named "economy-bot" with **robo.js**, designed to be a simple yet effective starting point for users. This template has been added to the templates folder within your repository.
```js
This contribution aligns with the spirit of #Hacktoberfest. Please #Squash it to `main` branch. Thanks 😊
```
---
> Please review and merge this pull request to make it available to the community. Thank you!
=> 💵 New Template: Starter Economy Bot Using Flashcore!

templates/economy-bot/src/commands/balance.ts, templates/economy-bot/src/commands/roll_dice.ts, templates/economy-bot/src/utils.ts
> - [x] Fixed Economy Bot Template, Unable to Choose number bug!
> - [x] Added **0.5x** multiplier
> - [x] Fix Error thrown on ` /balance ` command if user not registered!
=> Fix (templates/economy-bot): Bug causing user unable to choose dice number!

CONTRIBUTING.md
=> typo(CONTRIBUTING.md): pnpm changesets -> pnpm changeset

packages/create-robo/src/robo.ts
Creating a env.d.ts file for basic types autocomplete with .env file.
Note: the tsconfig.json file is only created after (at the same time) credentials are asked, that's why the "createEnvTsFile" method is at the end of the "askForDiscordCredentials" one, please, if this is an issue, let me know.
=> feat(create-robo): env.d.ts

packages/robo/src/cli/utils/utils.ts
packageName not being compliant described in issue #196
=> Fix(utils.ts): packageName

.changeset/lucky-kiwis-heal.md, packages/create-robo/src/index.ts
Added -k option, left extra comments to give a rough idea of what I think can de done
=> Kit option.

packages/sage/src/commands/generate.ts, packages/sage/src/commands/why.ts
I had to fix sage due to errors of import due to the new compiler owo  (the doctor command was broken)
=> fix(sage): getManifest

packages/robo/src/cli/commands/help.ts
=> fix(cli): removed doctor cmd from help menu

packages/sage/src/commands/upgrade.ts
=> fix(sage): upgrade cmd break when upgrading local pkg

packages/plugin-sync/src/core/server.ts
Refactored the WebSocket server to improve modularity and connection handling.
- Refactored **3** connection management modules.
- Enhanced liveness checks for **2** connection types.
- Optimized **4** state update mechanisms.
- Added error handling for incoming messages.
Improves performance, stability, and maintainability.
=> Refactor WebSocket Server to Enhance Connection Handling and State Management

docs/docs/plugins/directory.mdx
I hope I'm doing this right. Let me know if not
=> docs: added api-sync card in community plugins

packages/create-robo/src/index.ts
=> feat(create-robo): add "Web App" to initial prompt when no kit is there

docs/docs/cli/create-robo.mdx
https://github.com/Wave-Play/robo.js/commit/295f21d2498a13ea0dfc383fb0cb79793ede642b
=> docs(create-robo.mdx): show avaialabel kit

.changeset/tough-ants-serve.md, packages/plugin-modtools/.robo/manifest.json, packages/plugin-modtools/README.md, packages/plugin-modtools/src/commands/mod/ban.ts, packages/plugin-modtools/src/commands/mod/rules-msg/send.ts, packages/plugin-modtools/src/commands/mod/rules-msg/set-member-role.ts, packages/plugin-modtools/src/commands/mod/rules-msg/set-rules.ts, packages/plugin-modtools/src/events/interactionCreate/buttons-accept-rules.ts, packages/plugin-modtools/src/events/interactionCreate/modal-set-rules.ts, packages/plugin-modtools/src/events/messageCreate/user-not-accepted-rules.ts
Rules is a system where if a user sends a message with out member role the message is deleted and there prompted via dm to accept the rules. a message in the rules channel with I accept button
=> feat(moderation): Rules

.changeset/five-mice-guess.md, packages/robo/src/default/commands/help.ts
=> feat(default/help): Particular embeds for each command!

.changeset/funny-frogs-reply.md, packages/sage/src/commands/doctor.ts
=> patch(sage/doctor): import updated env manager

.github/workflows/zip-template.yml, scripts/zip.js
Let me know if you have any question about anything
=> feat(zip-templates): zipping templates for future download.

packages/sage/src/commands/upgrade.ts
Please review for further work on CI.
=> feat(sage/upgrade): auto accept option

packages/robo/src/cli/commands/help.ts
=> patch(help.ts): i think this isnt correct name

.changeset/famous-donuts-build.md, packages/robo/src/cli/utils/utils.ts
Added quotes around the URL on Windows, as there is & and it is counted as special character therefor making things crash. <3
=> fix(cli/login)

packages/create-robo/src/index.ts, packages/create-robo/src/robo.ts, packages/robo/src/cli/commands/dev.ts, packages/robo/src/cli/utils/cloudflared.ts
haha, second time is the charm 😅
=> feat(robo/cli) static cloudflare support

.changeset/real-mails-remember.md, packages/@robojs/trpc/src/events/_start.ts
This contains a fix for Windows and TRPC plugin.
Note: this goes along with <https://github.com/Wave-Play/robo.js> this PR.
=> fix(windows)
